# Generated by Django 6.0.4 on 2026-06-10 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('grupo', models.CharField(blank=True, max_length=1)),
            ],
            options={
                'ordering': ['grupo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('fase', models.CharField(choices=[('grupos', 'Fase de grupos'), ('32avos', '32avos de final'), ('octavos', 'Octavos de final'), ('cuartos', 'Cuartos de final'), ('semis', 'Semifinales'), ('tercer_puesto', 'Tercer puesto'), ('final', 'Final')], default='grupos', max_length=20)),
                ('grupo', models.CharField(blank=True, max_length=1)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('estadio', models.CharField(max_length=120)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('etiqueta_local', models.CharField(blank=True, max_length=100)),
                ('etiqueta_visitante', models.CharField(blank=True, max_length=100)),
                ('goles_local', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En vivo'), ('finalizado', 'Finalizado')], default='programado', max_length=20)),
                ('notas', models.CharField(blank=True, max_length=180)),
                ('equipo_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_local', to='core.equipo')),
                ('equipo_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_visitante', to='core.equipo')),
            ],
            options={
                'ordering': ['fecha', 'hora', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PartidoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='core.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'partido'), name='favorito_unico_por_usuario')],
            },
        ),
    ]
