# Generated by Django 6.0.4 on 2026-06-11 13:06

from django.db import migrations, models


def renombrar_32avos_a_16avos(apps, schema_editor):
    Partido = apps.get_model('core', 'Partido')
    Partido.objects.filter(fase='32avos').update(fase='16avos')


def renombrar_16avos_a_32avos(apps, schema_editor):
    Partido = apps.get_model('core', 'Partido')
    Partido.objects.filter(fase='16avos').update(fase='32avos')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prediccion'),
    ]

    operations = [
        migrations.RunPython(renombrar_32avos_a_16avos, renombrar_16avos_a_32avos),
        migrations.AlterField(
            model_name='partido',
            name='fase',
            field=models.CharField(choices=[('grupos', 'Fase de grupos'), ('16avos', '16avos de final'), ('octavos', 'Octavos de final'), ('cuartos', 'Cuartos de final'), ('semis', 'Semifinales'), ('tercer_puesto', 'Tercer puesto'), ('final', 'Final')], default='grupos', max_length=20),
        ),
    ]
