# Generated by Django 6.0.4 on 2026-06-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_partido_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='canales_argentina',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='partido',
            name='streaming_argentina',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='partido',
            name='transmision_notas',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
