# Generated by Django 6.0.4 on 2026-06-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partido_canales_argentina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='arbitro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partido',
            name='arbitro_nacionalidad',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='partido',
            name='escudo_local_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='escudo_visitante_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='etapa_api',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='partido',
            name='evento_actualizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='football_data_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='grupo_api',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='partido',
            name='jornada',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
