# Generated by Django 6.0.4 on 2026-06-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_equipofavorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='codigo_fifa',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tecnico',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='JugadorSeleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=120)),
                ('camiseta', models.CharField(blank=True, max_length=80)),
                ('posicion', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=12)),
                ('club', models.CharField(blank=True, max_length=140)),
                ('altura_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('internacionalidades', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='core.equipo')),
            ],
            options={
                'ordering': ['equipo__nombre', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('equipo', 'orden'), name='jugador_unico_por_equipo_y_orden')],
            },
        ),
    ]
