# Generated by Django 6.0.4 on 2026-06-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_equipo_codigo_fifa_equipo_tecnico_jugadorseleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='tecnico_apellidos',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tecnico_nacionalidad',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tecnico_nombre_tabla',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tecnico_nombres',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jugadorseleccion',
            name='apellidos',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='jugadorseleccion',
            name='nombre_camiseta',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='jugadorseleccion',
            name='nombre_tabla',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jugadorseleccion',
            name='nombres',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
