# Generated by Django 6.0.4 on 2026-06-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipo_tecnico_apellidos_equipo_tecnico_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='estado_api',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
